site_name: ZeroDiff
site_description: ZeroDiff Documentation
site_author: Jeff Williams
site_url: https://zerodiff.org/

nav:
- Home: index.md
- Beginners:
    - Overivew: beginners/overview.md
    - Kaizen/CPI: beginners/kaizen.md
    - Design: beginners/design.md
    - User Editable Doc Repo: beginners/user_docs.md
    - All Designs To Github: beginners/doc_control.md
    - EE Checklist: hardware/pcb_checklist.md
    - Firmware Checklist: firmware/checklist.md
    - CI Server: beginners/tdd_ci.md
- Design:
    - User Empathy: design/empathy.md
    - First Principles: design/essential_user_task.md
    - Make Fewer Things: design/fewer.md
    - Teach, Don't Lead: design/teach.md
    - What's Testable?: design/testable.md
    - Ethnographic Study: design/ethno_study.md
    - Design Sprint: design/sprint.md
- Hardware:
    - Top-Level Object Dev: hardware/top_level.md
    - PCB/A:
        - PCB/A Dev: hardware/pcba.md
        - Release CheckList: hardware/pcb_checklist.md
    - MechE: 
        - MechE Dev: hardware/mech_eng.md
        - Release CheckList: hardware/meche_checklist.md
        - Test Criteria: hardware/mech_eng_test.md
        - Process Improvement: hardware/process_improvement.md
    - Firmware:
        - Firmware Dev: firmware/dev.md
        - Release Checklist: firmware/checklist.md
    - Vendors:
        - Trust as a Tool: vendor/trust.md
        - Assembly, Fab Notes: vendor/fab.md
        - ECOs - Yes, No, Maybe: vendor/eco.md
- Test:
    - Automated Monkey Tests: test/monkey.md
- Glossary: glossary.md
- About:
    - Why ZeroDiff?: about/why.md
    - Contribute: about/contribute.md
    - License: about/license.md
theme:
  name: material
  custom_dir: theme-overrides
  favicon: icons/favicon.ico
  logo: icons/zerodiff.svg
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    tabs: true
    instant: true

plugins:
  - search:
      prebuild_index: true
  - redirects:
      redirect_maps:
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zero-diff
    - icon: fontawesome/solid/envelope-square
      link: http://eepurl.com/dl_CsD

markdown_extensions:
  - tables
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_url: https://github.com/zero-diff/zerodiff/
copyright: <a href="https://tinyletter.com/zerodiff/archive">ZeroDiff TinyLetter Blog</a><br>Copyright &copy; 2020 <a href="https://github.com/0x6a77">Jeff Williams</a> under BSD-3 License

extra_css:
  - ./js/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.6.4/mermaid.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.js
  - https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.5.1/snap.svg-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.0.5/MathJax.js?config=TeX-MML-AM_CHTML
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.10.2/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.13.0/flowchart.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/webfont/1.6.28/webfontloader.js
#  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-snap-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.6.4/mermaid.min.js
  - js/sequence-diagram-rafael-min.js
#  - js/sequence-diagram-snap-min.js
  - js/extra.js

google_analytics:
  - UA-78164923-1
  - auto